a = int(input("Nhập giá trị a: "))
b = int(input("Nhập giá trị b: "))
print("Ketqua a+b:", a + b)
print("Ketqua a-b:", a - b)
print("Ketqua a*b:", a * b)
print("Ketqua a/b:", a / b)
print("Ketqua a//b:", a // b)
print("Ketqua a%b:", a % b)
print("Ketqua a**b:", a ** b)
print("Ketqua -a:", -a)
print ("a is b?", a is b)
print ("a is not b?", a is not b)